apiVersion: v1
kind: Service
metadata:
  name: employee-management-system
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: employee-management-system
